name: 'healthcare_dq'
version: '1.0.0'
config-version: 2

profile: 'healthcare_dq'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  healthcare_dq:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
