-- Healthcare Data Quality Framework - Snowflake Schemas

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.EHR_STAGING;

CREATE TABLE IF NOT EXISTS HEALTHCARE_DB.EHR_STAGING.EHR_RECORDS (
    PATIENT_ID          VARCHAR(50)     NOT NULL,
    ENCOUNTER_ID        VARCHAR(100)    NOT NULL,
    SOURCE_FORMAT       VARCHAR(10)     NOT NULL,
    SOURCE_SYSTEM       VARCHAR(50),
    EXTRACTED_AT_UTC    TIMESTAMP_NTZ   NOT NULL,
    RAW_PAYLOAD         VARIANT,
    LOADED_AT_UTC       TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_VERSION    VARCHAR(20),
    CONSTRAINT PK_EHR_RECORDS PRIMARY KEY (ENCOUNTER_ID)
);

CREATE TABLE IF NOT EXISTS HEALTHCARE_DB.EHR_STAGING.DQ_RESULTS (
    DQ_RUN_ID           VARCHAR(36)     NOT NULL DEFAULT UUID_STRING(),
    CHECK_NAME          VARCHAR(100)    NOT NULL,
    PASSED              BOOLEAN         NOT NULL,
    RECORDS_CHECKED     INTEGER         NOT NULL,
    RECORDS_FAILED      INTEGER         NOT NULL,
    ACCURACY_PCT        FLOAT           NOT NULL,
    DETAILS             VARCHAR(1000),
    RUN_AT_UTC          TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_RESULTS PRIMARY KEY (DQ_RUN_ID, CHECK_NAME)
);
